// GENERATED by scripts/authoring/integrate_modules.py – do not edit by hand.
// Static imports keep the content in the bundle (static export, no runtime file access).
import modM01 from "@content/modules/M01.json";
import modM02 from "@content/modules/M02.json";
import modM03 from "@content/modules/M03.json";
import modM04 from "@content/modules/M04.json";
import modM05 from "@content/modules/M05.json";
import modM06 from "@content/modules/M06.json";
import modM07 from "@content/modules/M07.json";
import modM08 from "@content/modules/M08.json";
import qM01 from "@content/questions/M01.json";
import qM02 from "@content/questions/M02.json";
import qM03 from "@content/questions/M03.json";
import qM04 from "@content/questions/M04.json";
import qM05 from "@content/questions/M05.json";
import qM06 from "@content/questions/M06.json";
import qM07 from "@content/questions/M07.json";
import qM08 from "@content/questions/M08.json";
import simSIM001 from "@content/scenarios/SIM-001.json";
import simSIM002 from "@content/scenarios/SIM-002.json";
import simSIM003 from "@content/scenarios/SIM-003.json";
import simSIM004 from "@content/scenarios/SIM-004.json";
import simSIM005 from "@content/scenarios/SIM-005.json";
import simSIM006 from "@content/scenarios/SIM-006.json";
import simSIM007 from "@content/scenarios/SIM-007.json";
import simSIM008 from "@content/scenarios/SIM-008.json";
import simSIM009 from "@content/scenarios/SIM-009.json";
import simSIM010 from "@content/scenarios/SIM-010.json";

export const moduleFiles: unknown[] = [modM01, modM02, modM03, modM04, modM05, modM06, modM07, modM08];
export const questionFiles: unknown[][] = [qM01, qM02, qM03, qM04, qM05, qM06, qM07, qM08];
export const scenarioFiles: unknown[] = [simSIM001, simSIM002, simSIM003, simSIM004, simSIM005, simSIM006, simSIM007, simSIM008, simSIM009, simSIM010];
