// GENERATED by scripts/authoring/integrate_modules.py – do not edit by hand.
// Static imports keep the content in the bundle (static export, no runtime file access).
import modM01 from "@content/modules/M01.json";
import modM02 from "@content/modules/M02.json";
import modM04 from "@content/modules/M04.json";
import qM01 from "@content/questions/M01.json";
import qM02 from "@content/questions/M02.json";
import qM04 from "@content/questions/M04.json";
import simSIM001 from "@content/scenarios/SIM-001.json";
import simSIM002 from "@content/scenarios/SIM-002.json";
import simSIM003 from "@content/scenarios/SIM-003.json";
import simSIM004 from "@content/scenarios/SIM-004.json";
import simSIM006 from "@content/scenarios/SIM-006.json";

export const moduleFiles: unknown[] = [modM01, modM02, modM04];
export const questionFiles: unknown[][] = [qM01, qM02, qM04];
export const scenarioFiles: unknown[] = [simSIM001, simSIM002, simSIM003, simSIM004, simSIM006];
