# Integrates authored modules (content/modules/MXX.json + questions + scenario + sources-additions + concept-links)
# into the shared content files. Idempotent. Run after authors deliver:  python3 scripts/authoring/integrate_modules.py
#  1. merges content/sources-additions/*.json into content/sources.json; a source that already exists under another
#     ID (same DOI or same URL+title) is mapped to the existing ID and references are rewritten in the module files
#  2. links objectives into content/concepts.json from content/concept-links/*.json
#  3. marks modules with content as "verfuegbar" in curriculum.json
#  4. generates src/lib/content/registry.ts (static imports – the static export cannot glob at runtime)
import json, glob, os, re, sys
# Optional: restrict to modules whose authoring is finished, e.g. `integrate_modules.py M04 M05`.
ONLY = set(sys.argv[1:]) or None
ok = lambda mid: ONLY is None or mid in ONLY or mid in ("M01", "M02")
R = lambda p: json.load(open(p))
def W(p, d): open(p, "w").write(json.dumps(d, ensure_ascii=False, indent=2) + "\n")
def norm(s): return re.sub(r"[^a-z0-9]", "", (s or "").lower())

sources = R("content/sources.json")
by_id = {s["id"]: s for s in sources}
def key_doi(s): return norm(s.get("doi"))
def key_url(s): return norm(s.get("url")) + "|" + norm(s.get("title"))[:40]
idx_doi = {key_doi(s): s["id"] for s in sources if s.get("doi")}
idx_url = {key_url(s): s["id"] for s in sources}

remap_all = {}
for f in sorted(glob.glob("content/sources-additions/*.json")):
    mod = os.path.basename(f)[:-5]
    if not ok(mod): continue
    remap = {}
    for s in R(f):
        dup = (s.get("doi") and idx_doi.get(key_doi(s))) or idx_url.get(key_url(s))
        if s["id"] in by_id:
            if by_id[s["id"]] != s and not dup: raise SystemExit(f"ID-Kollision {s['id']} in {f}")
            continue
        if dup:
            remap[s["id"]] = dup
            continue
        sources.append(s); by_id[s["id"]] = s
        if s.get("doi"): idx_doi[key_doi(s)] = s["id"]
        idx_url[key_url(s)] = s["id"]
    if remap:
        remap_all[mod] = remap
        for p in [f"content/modules/{mod}.json", f"content/questions/{mod}.json"] + glob.glob("content/scenarios/*.json"):
            if not os.path.exists(p): continue
            txt = open(p).read()
            new = re.sub(r'"(SRC-\d{3})"', lambda m: '"%s"' % remap.get(m.group(1), m.group(1)), txt)
            if new != txt: open(p, "w").write(new)
sources.sort(key=lambda s: s["id"])
W("content/sources.json", sources)

concepts = R("content/concepts.json")
for f in sorted(glob.glob("content/concept-links/*.json")):
    if not ok(os.path.basename(f)[:-5]): continue
    for cid, objs in R(f).items():
        c = next((x for x in concepts if x["id"] == cid), None)
        if not c: raise SystemExit(f"Unbekanntes Konzept {cid} in {f}")
        c["objectiveIds"] = sorted(set(c["objectiveIds"]) | set(objs))
W("content/concepts.json", concepts)

mods = sorted(m for m in (os.path.basename(p)[:-5] for p in glob.glob("content/modules/M*.json")) if ok(m))
cur = R("content/curriculum.json")
for c in cur:
    if c["id"] in mods: c["status"] = "verfuegbar"
W("content/curriculum.json", cur)
for m in mods:
    d = R(f"content/modules/{m}.json")
    if d.get("status") != "verfuegbar":
        d["status"] = "verfuegbar"; W(f"content/modules/{m}.json", d)

def sim_ok(p):
    links = (R(p).get("ai") or {}).get("lessonLinks") or []
    return not links or ok(links[0].split("-")[0])
sims = sorted(os.path.basename(p)[:-5] for p in glob.glob("content/scenarios/SIM-*.json") if sim_ok(p))
v = lambda s: re.sub(r"[^A-Za-z0-9]", "", s)
lines = ["// GENERATED by scripts/authoring/integrate_modules.py – do not edit by hand.",
         "// Static imports keep the content in the bundle (static export, no runtime file access)."]
lines += [f'import mod{m} from "@content/modules/{m}.json";' for m in mods]
lines += [f'import q{m} from "@content/questions/{m}.json";' for m in mods if os.path.exists(f"content/questions/{m}.json")]
lines += [f'import sim{v(s)} from "@content/scenarios/{s}.json";' for s in sims]
lines += ["", f"export const moduleFiles: unknown[] = [{', '.join('mod'+m for m in mods)}];",
          f"export const questionFiles: unknown[][] = [{', '.join('q'+m for m in mods if os.path.exists(f'content/questions/{m}.json'))}];",
          f"export const scenarioFiles: unknown[] = [{', '.join('sim'+v(s) for s in sims)}];", ""]
open("src/lib/content/registry.ts", "w").write("\n".join(lines))
print("modules", mods, "| scenarios", len(sims), "| sources", len(sources), "| remapped", remap_all)
