# One-off authoring script for Module 2 "Professionelle Kommunikation". JSON is the source of truth afterwards.
import json
def book(ch,title,paras,src): return {"kind":"book","chapter":ch,"title":title,"paragraphs":paras,"sourceIds":src}
def skill(name,cat,what,how,why,evidence,example,boundary,src):
    return {"kind":"skill","name":name,"category":cat,"what":what,"how":how,"why":why,"evidence":evidence,"example":example,"boundary":boundary,"sourceIds":src}
def myth(c,r,src): return {"kind":"myth","claim":c,"reality":r,"sourceIds":src}
def check(q): return {"kind":"check","questionId":q}
def text(t,b): return {"kind":"text","title":t,"body":b}

O=[("LO-M02-01","Nachrichten klar, kurz und mobil lesbar formulieren.","anwenden"),
   ("LO-M02-02","Aktives Zuhören im Chat und am Telefon zeigen (Paraphrase, Benennen, Folgefrage).","anwenden"),
   ("LO-M02-03","Fragetypen gezielt einsetzen und in eine sinnvolle Reihenfolge bringen (Trichter).","anwenden"),
   ("LO-M02-04","Gespräche respektvoll eröffnen und Erlaubnis einholen – im Chat und am Telefon.","anwenden"),
   ("LO-M02-05","Tonfall, Anrede und Stil an Kanal und Person anpassen.","analysieren"),
   ("LO-M02-06","Vertrauen durch Kompetenz, Wohlwollen und Verlässlichkeit aufbauen.","verstehen"),
   ("LO-M02-07","Mit unterschiedlichen Kundentypen umgehen, ohne Menschen in Schubladen zu stecken.","bewerten")]

lessons=[
{"id":"M02-L01","title":"Klar schreiben – ein Gedanke pro Nachricht","objectiveIds":["LO-M02-01"],"sourceIds":["SRC-066","SRC-050"],
 "blocks":[
  text("Worum es geht","Im Chat Setting ist dein Text alles, was der Kunde von dir sieht. Kein Lächeln, keine Stimme, kein Händedruck. In dieser Lektion lernst du, Nachrichten zu schreiben, die auf einem Handy in drei Sekunden verstanden werden."),
  book("Kapitel 2.1","Das Drei-Sekunden-Prinzip",[
   "Die meisten Menschen lesen Nachrichten von Unternehmen nebenbei: an der Bushaltestelle, in der Mittagspause, zwischen zwei anderen Chats. Sie entscheiden in wenigen Sekunden, ob sie antworten. Deine Nachricht muss in dieser Zeit drei Fragen beantworten: Wer schreibt mir? Warum? Was soll ich jetzt tun?",
   "Daraus ergibt sich die wichtigste Regel des Chat Settings: ein Gedanke pro Nachricht. Wer in einer Nachricht begrüßt, das Unternehmen vorstellt, drei Fragen stellt und einen Link schickt, bekommt selten eine vollständige Antwort. Meist antwortet der Kunde auf den letzten Satz – oder gar nicht, weil die Nachricht nach Arbeit aussieht.",
   "Das Hamburger Verständlichkeitsmodell aus der Psychologie nennt vier Merkmale verständlicher Texte: Einfachheit, Gliederung, Kürze und ein wenig Anregung. Übersetzt in Chat-Sprache heißt das: kurze, vertraute Wörter; ein klarer Aufbau (Anlass – Frage); keine Füllsätze; und ein persönlicher Bezug, der die Nachricht lebendig macht.",
   "Konkrete Faustregeln: Sätze möglichst unter 15 Wörtern. Keine Abkürzungen, die nur du kennst. Keine Fachbegriffe ohne Erklärung („Ihre JAZ“ versteht niemand). Zahlen als Ziffern schreiben. Und die Frage ans Ende stellen – dort, wo der Blick des Lesers hängen bleibt.",
   "Ein guter Test: Lies deine Nachricht vor dem Absenden so, als wärst du der Kunde und hättest gerade wenig Zeit. Würdest du antworten? Wenn du zögerst, kürze. Fast jede erste Fassung wird besser, wenn man ein Drittel streicht."
  ],["SRC-066","SRC-050"]),
  skill("Anlass – Frage","schreiben","Jede Nachricht besteht aus einem kurzen Anlass und genau einer Frage am Ende.",
   ["Satz 1: Anlass oder Bezug („Danke für Ihre Anfrage zum Speicher.“)","Optional Satz 2: kurzer Grund („Damit wir Sie passend beraten …“)","Letzter Satz: eine einzige, offene Frage."],
   "Der Kunde weiß sofort, worum es geht und was er tun soll. Eine einzige Frage ist leicht zu beantworten.",
   "Verständlichkeitsforschung (Langer, Schulz von Thun & Tausch): Einfachheit, Gliederung, Kürze. Für Chat-Formate als Praxisheuristik übertragen (Expertenmeinung).",
   "„Danke für Ihre Anfrage zum Stromspeicher, Frau Lenz! Was möchten Sie mit dem Speicher vor allem erreichen?“",
   "Kurz heißt nicht kühl. Eine freundliche Begrüßung und der Name gehören dazu.",["SRC-066"]),
  {"kind":"example","title":"Vorher – nachher","body":"Vorher (71 Wörter): „Hallo, vielen herzlichen Dank für Ihre Anfrage bezüglich unserer innovativen Speicherlösungen, wir sind ein führender Anbieter im Bereich erneuerbare Energien mit langjähriger Erfahrung. Gerne würde ich Ihnen ein paar Fragen stellen: Wie groß ist Ihre PV-Anlage, wie hoch ist Ihr Verbrauch, haben Sie schon Angebote, und wann hätten Sie Zeit für einen Termin? Hier ist auch unser Kalenderlink …“\n\nNachher (22 Wörter): „Hallo Frau Lenz, hier ist Jonas von SolarNord – danke für Ihre Anfrage! Was möchten Sie mit dem Speicher vor allem erreichen?“"},
  check("Q-M02-001"),check("Q-M02-002"),
  {"kind":"reflect","prompt":"Nimm eine Nachricht, die du kürzlich geschrieben hast (privat oder beruflich). Wie viele Gedanken stecken darin? Wie würde die Version mit einem Gedanken aussehen?"}
 ],
 "summary":["Ein Gedanke und eine Frage pro Nachricht.","Kurze Sätze, vertraute Wörter, keine unerklärten Fachbegriffe.","Frage ans Ende stellen.","Vor dem Absenden ein Drittel streichen."]},

{"id":"M02-L02","title":"Aktiv zuhören, auch im Chat","objectiveIds":["LO-M02-02"],"sourceIds":["SRC-055","SRC-054","SRC-060","SRC-065"],
 "blocks":[
  text("Worum es geht","Zuhören ist die unterschätzteste Verkaufsfähigkeit. In dieser Lektion lernst du drei Werkzeuge, mit denen du Zuhören sichtbar machst: Paraphrasieren, Benennen und die Folgefrage."),
  book("Kapitel 2.2","Zuhören, das man sehen kann",[
   "Viele Menschen glauben, gutes Zuhören bedeute, still zu sein. Im Gespräch mit Kunden reicht das nicht. Der Kunde muss merken, dass du verstanden hast – und im Chat kann er dich nicht nicken sehen. Zuhören muss deshalb in deinen Worten sichtbar werden.",
   "Das erste Werkzeug ist die Paraphrase: Du gibst das Gesagte in eigenen Worten wieder. „Wenn ich Sie richtig verstehe, geht es Ihnen vor allem darum, unabhängiger vom Strompreis zu werden?“ In einem Experiment mit 115 Teilnehmenden fühlten sich Menschen, deren Aussagen so wiedergegeben wurden, deutlich stärker verstanden als Menschen, die nur ein „Okay“ oder einen gut gemeinten Ratschlag erhielten. Wichtig: Die Paraphrase ist eine Frage, keine Behauptung. Der Kunde darf korrigieren.",
   "Das zweite Werkzeug ist das Benennen von Gefühlen. Wenn ein Kunde schreibt „Ich habe schon drei Angebote bekommen und blicke gar nicht mehr durch“, steckt darin Frust und Überforderung. Ein Satz wie „Klingt, als wäre das gerade ziemlich unübersichtlich“ zeigt, dass du nicht nur die Fakten, sondern auch die Lage verstanden hast. Laborstudien zeigen, dass das Benennen von Gefühlen emotionale Reaktionen dämpfen kann. In Verhandlungstrainings ist die Technik als „Labeling“ bekannt. Übertreib es nicht: Ein Gefühl zu benennen ist kein Therapiegespräch.",
   "Das dritte Werkzeug kennst du aus Modul 1: die Folgefrage. Sie knüpft an ein konkretes Wort des Kunden an und vertieft es. Eine Studie mit echten Gesprächen fand, dass Menschen, die mehr Folgefragen stellen, als deutlich sympathischer wahrgenommen werden – weil sie als aufmerksam und zugewandt erlebt werden.",
   "Und was ist das Gegenteil von Zuhören? Drei typische Fehler: sofort eine Lösung anbieten („Dann brauchen Sie unseren Speicher XL!“), das Thema wechseln („Wann haben Sie Zeit?“) und von sich erzählen („Das kenne ich, bei mir war das auch so …“). Alle drei signalisieren: Mir geht es um mich, nicht um dich."
  ],["SRC-055","SRC-060","SRC-054","SRC-065"]),
  skill("Paraphrase als Frage","gespraech","Das Gesagte in eigenen Worten wiedergeben und um Bestätigung bitten.",
   ["Kern der Aussage herausfiltern (nicht alles wiederholen).","Mit „Wenn ich Sie richtig verstehe …“ oder „Also …“ einleiten.","In eigenen Worten formulieren, nicht wörtlich kopieren.","Mit einer Frage enden: „… stimmt das?“"],
   "Der Kunde fühlt sich verstanden und kann Missverständnisse sofort korrigieren.",
   "Weger et al. (2014): Aktives Zuhören erhöhte das Gefühl, verstanden zu werden, gegenüber Ratschlag oder bloßer Bestätigung.",
   "Kunde: „Unser Dach ist eigentlich zu klein, aber wir wollen trotzdem was für die Umwelt tun.“ → „Also ist Ihnen der Umweltaspekt wichtiger als die maximale Ersparnis – habe ich das richtig verstanden?“",
   "Nicht ständig paraphrasieren – ein- bis zweimal pro Gespräch an wichtigen Stellen reicht.",["SRC-055"]),
  skill("Gefühle benennen","psychologie","Die erkennbare Lage oder Emotion des Kunden in einem vorsichtigen Satz aussprechen.",
   ["Signal erkennen (Frust, Unsicherheit, Zeitdruck, Freude).","Vorsichtig benennen: „Klingt, als …“, „Wirkt, als …“.","Pause lassen – nicht sofort eine Lösung anhängen.","Danach eine offene Frage stellen."],
   "Wer sich in seiner Lage verstanden fühlt, ist eher bereit, weiterzusprechen und Details zu teilen.",
   "Lieberman et al. (2007): Affekt-Benennung dämpft emotionale Reaktionen (Laborbefund). Voss (2016): Praxistechnik „Labeling“ – Erfahrungswissen, nicht systematisch evaluiert.",
   "„Klingt, als wären die vielen Angebote gerade eher verwirrend als hilfreich. Was würde Ihnen am meisten helfen, Klarheit zu bekommen?“",
   "Keine Diagnosen („Sie haben Angst vor …“) und kein Ausnutzen von Emotionen, um Druck zu machen.",["SRC-060","SRC-065"]),
  check("Q-M02-003"),check("Q-M02-004"),check("Q-M02-005")
 ],
 "summary":["Zuhören muss im Chat sichtbar werden.","Paraphrase: Kern in eigenen Worten, als Frage.","Gefühle vorsichtig benennen, dann offen fragen.","Nicht sofort Lösungen, Themenwechsel oder eigene Geschichten."]},

{"id":"M02-L03","title":"Fragetechniken vertieft – der Fragetrichter","objectiveIds":["LO-M02-03"],"sourceIds":["SRC-013","SRC-054","SRC-050"],
 "blocks":[
  text("Worum es geht","Gute Fragen sind das wichtigste Werkzeug eines Setters. In dieser Lektion lernst du fünf Fragetypen und wie du sie im „Trichter“ von breit nach konkret ordnest."),
  book("Kapitel 2.3","Fragen, die Türen öffnen",[
   "Fragen sind nicht neutral. Jede Frage lenkt die Aufmerksamkeit des Gegenübers. „Was stört Sie an Ihrer aktuellen Heizung?“ lenkt auf Probleme. „Was wäre Ihnen bei einer neuen Heizung am wichtigsten?“ lenkt auf Ziele. Beide sind gute Fragen – aber an unterschiedlichen Stellen im Gespräch.",
   "Für Setter sind fünf Fragetypen besonders nützlich. Offene Fragen (Was? Wie? Welche?) öffnen das Gespräch. Geschlossene Fragen (Ja/Nein) klären Fakten. Skalenfragen („Auf einer Skala von 1 bis 10, wie dringend ist das Thema für Sie?“) machen Unklares messbar. Klärungsfragen („Was meinen Sie genau mit ‚zu teuer‘?“) verhindern Missverständnisse. Und Zusammenfassungsfragen („Habe ich richtig verstanden, dass …?“) sichern das Ergebnis.",
   "Die Reihenfolge folgt dem Trichter-Prinzip: oben breit, unten eng. Du beginnst mit einer offenen Frage nach Anlass oder Ziel, wirst mit Folgefragen konkreter, klärst dann die Pflichtkriterien mit geschlossenen Fragen und schließt mit einer Zusammenfassung. Wer andersherum beginnt – mit einer Reihe geschlossener Fragen – wirkt wie ein Fragebogen und erfährt nie, was den Kunden eigentlich bewegt.",
   "Die SPIN-Methode von Neil Rackham sortiert Fragen in Situation, Problem, Implikation und Nutzen. Für Setter sind vor allem Situations- und Problemfragen relevant. Implikationsfragen („Was passiert, wenn die Heizung im Winter ausfällt?“) gehören eher ins Beratungsgespräch – im Erstkontakt wirken sie schnell manipulativ, weil sie Ängste verstärken können.",
   "Zwei Fragetypen solltest du meiden: Suggestivfragen („Sie wollen doch auch sparen, oder?“) und Warum-Fragen, die wie ein Vorwurf klingen („Warum haben Sie das nicht früher gemacht?“). Wenn du nach Gründen fragen willst, nutze „Was hat dazu geführt …?“ – die Frage ist dieselbe, der Ton ist ein anderer."
  ],["SRC-013","SRC-054","SRC-050"]),
  {"kind":"workedExample","title":"Ein Fragetrichter in fünf Nachrichten","steps":[
   "Offen (Anlass): „Was hat Sie dazu gebracht, sich gerade jetzt mit einem Speicher zu beschäftigen?“",
   "Folgefrage: „Sie sagten, der Strompreis macht Ihnen Sorgen – wie hoch ist Ihr Abschlag ungefähr?“",
   "Skalenfrage: „Wie dringend ist das Thema für Sie, auf einer Skala von 1 bis 10?“",
   "Geschlossen (Pflichtkriterium): „Haben Sie bereits eine PV-Anlage auf dem Dach?“",
   "Zusammenfassung: „Also: PV-Anlage vorhanden, Abschlag deutlich gestiegen, Dringlichkeit 8 von 10 – stimmt das so?“"
  ]},
  skill("Die Skalenfrage","gespraech","Ein unklares Gefühl („irgendwie dringend“) in eine Zahl übersetzen lassen.",
   ["Frage mit klarer Skala stellen (1–10).","Zahl annehmen, nicht bewerten.","Nachfragen: „Was müsste passieren, damit es eine Zahl höher wäre?“ oder „Warum nicht niedriger?“"],
   "Zahlen machen Dringlichkeit und Unsicherheit vergleichbar und öffnen eine natürliche Folgefrage.",
   "Verbreitete Technik aus Beratung und lösungsorientierter Gesprächsführung (Expertenmeinung); keine spezifische Studie für Vertrieb.",
   "„Wie sicher sind Sie sich auf einer Skala von 1 bis 10, dass Sie das Projekt dieses Jahr angehen?“ – „6.“ – „Was fehlt noch zu einer 8?“",
   "Die Antwort ist eine Selbsteinschätzung, kein Versprechen. Nicht als Druckmittel verwenden („Sie sagten doch 8!“).",["SRC-050"]),
  check("Q-M02-006"),check("Q-M02-007"),check("Q-M02-008"),check("Q-M02-009")
 ],
 "summary":["Fünf Fragetypen: offen, geschlossen, Skala, Klärung, Zusammenfassung.","Trichter: breit beginnen, konkret enden.","SPIN im Erstkontakt vor allem Situation und Problem.","Keine Suggestiv- und Vorwurfs-Warum-Fragen."]},

{"id":"M02-L04","title":"Eröffnen und Erlaubnis holen – Chat und Telefon","objectiveIds":["LO-M02-04"],"sourceIds":["SRC-052","SRC-053","SRC-058","SRC-019"],
 "blocks":[
  text("Worum es geht","Die ersten Sekunden entscheiden, ob ein Gespräch überhaupt stattfindet. In dieser Lektion lernst du Eröffnungen für Chat und Telefon, die respektvoll und wirksam sind."),
  book("Kapitel 2.4","Der erste Eindruck hat drei Teile",[
   "Eine gute Eröffnung beantwortet drei Fragen, bevor der Kunde sie stellen muss: Wer bist du? Warum meldest du dich? Darf es jetzt sein? Am Telefon kommt eine vierte hinzu: Wie lange dauert es? Wer diese Fragen beantwortet, nimmt dem Gegenüber die Unsicherheit – und Unsicherheit ist der häufigste Grund, warum Menschen abblocken.",
   "Im Chat funktioniert die Eröffnung über Bezug und Kürze. Der Bezug („Sie hatten gestern unseren Speicher-Ratgeber angefordert“) zeigt, dass du kein Fremder bist. Die Kürze zeigt Respekt vor seiner Zeit. Am Telefon kommt die Stimme dazu: langsam sprechen, den eigenen Namen deutlich sagen, nach dem ersten Satz eine echte Pause lassen. Viele Einsteiger reden in den ersten zehn Sekunden zu schnell, weil sie nervös sind – und genau dann entsteht der Eindruck eines Callcenters.",
   "Die Erlaubnisfrage („Passt es gerade für zwei Minuten?“) wirkt auf den ersten Blick riskant: Was, wenn der Kunde Nein sagt? Dann hast du eine wertvolle Information bekommen und vereinbarst einen besseren Zeitpunkt. Ein Gespräch, das jemand gegen seinen Willen führt, bringt dir ohnehin nichts. Wer gefragt wird, fühlt sich respektiert – und respektierte Menschen sind offener.",
   "Ergänzend kannst du einen Grund nennen („… damit wir Sie passend beraten können“) und Freiheit betonen („Wenn es gerade nicht passt, schreibe ich Ihnen gern später“). Beide Prinzipien sind psychologisch untersucht: Begründungen erhöhen die Zustimmung zu kleinen Bitten, und das Betonen von Entscheidungsfreiheit kann Widerstand senken. Die Effekte sind in strengen Studien kleiner als oft behauptet – aber sie sind ehrlich, und das allein ist schon ein Grund, sie zu nutzen.",
   "Und rechtlich? Eine Eröffnung ist nur dann sauber, wenn der Kontakt überhaupt zulässig ist. Im Inbound-Fall, wenn der Kunde angefragt und dem Kanal zugestimmt hat, ist das gegeben. Rufst du ohne Einwilligung eine Privatperson zu Werbezwecken an, hilft dir die beste Eröffnung nichts."
  ],["SRC-058","SRC-052","SRC-053","SRC-019"]),
  skill("Die 4-Satz-Telefoneröffnung","gespraech","Am Telefon in vier kurzen Sätzen Vertrauen und Orientierung schaffen.",
   ["Name + Unternehmen: „Guten Tag Herr Weber, hier ist Mira von SolarNord.“","Bezug: „Sie hatten gestern online eine Anfrage zur PV-Anlage gestellt.“","Zeitrahmen + Erlaubnis: „Ich habe zwei, drei kurze Fragen, das dauert etwa fünf Minuten – passt es gerade?“","Pause. Wirklich warten."],
   "Der Angerufene weiß sofort, wer anruft, warum, wie lange – und dass er entscheiden darf.",
   "Kombination aus Begründung (Langer et al. 1978) und Autonomie (Carpenter 2013; Effekt in strengen Studien klein). Pausen-Empfehlung ist Praxiswissen.",
   "„Guten Tag Frau Kaya, hier ist Jonas von WärmeWerk Nord. Sie hatten uns wegen einer Wärmepumpe geschrieben. Ich hätte drei kurze Fragen, etwa fünf Minuten – passt es gerade, oder lieber später?“",
   "Nur bei zulässigem Kontakt (Einwilligung bzw. Inbound-Anfrage). Die genannte Dauer muss stimmen.",["SRC-058","SRC-052","SRC-053","SRC-019"]),
  myth("„Die ersten sieben Sekunden entscheiden alles – und 93 % der Wirkung kommt aus Stimme und Körpersprache.“",
   "Die berühmte 7-38-55-Regel stammt aus Experimenten von Albert Mehrabian zu widersprüchlichen Gefühlsbotschaften mit einzelnen Wörtern. Mehrabian selbst betont, dass sie nicht auf Kommunikation allgemein übertragbar ist. Was du sagst, zählt – im Chat sogar fast ausschließlich.",["SRC-063"]),
  check("Q-M02-010"),check("Q-M02-011"),check("Q-M02-012")
 ],
 "summary":["Wer, warum, darf es jetzt sein – am Telefon plus: wie lange.","Langsam sprechen, Pause nach der Eröffnung.","Erlaubnisfrage ist Respekt und liefert Information.","Gute Eröffnung ersetzt keine Einwilligung."]},

{"id":"M02-L05","title":"Tonfall, Anrede und Kanal","objectiveIds":["LO-M02-05"],"sourceIds":["SRC-061","SRC-063","SRC-050"],
 "blocks":[
  text("Worum es geht","Derselbe Inhalt kann freundlich, steif oder aufdringlich wirken – je nach Ton. In dieser Lektion lernst du, deinen Stil an Kanal und Person anzupassen."),
  book("Kapitel 2.5","Der richtige Ton am richtigen Ort",[
   "Instagram ist nicht LinkedIn, und WhatsApp ist nicht E-Mail. Jeder Kanal hat eigene Gewohnheiten. Auf Instagram duzen sich viele, Nachrichten sind kurz, ein Emoji ist normal. In einer E-Mail an einen Geschäftsführer wäre dasselbe unpassend. Deine erste Aufgabe ist deshalb, den Kanal zu lesen – und im Zweifel eine Stufe förmlicher zu beginnen, als du denkst.",
   "Die Anrede folgt einer einfachen Regel: Spiegel den Kunden, aber nie nach unten. Wenn der Kunde dich duzt und es zum Auftraggeber passt, darfst du zurückduzen. Wenn er siezt, siezt du. Wenn du unsicher bist, siezt du. Für Marken mit Du-Kultur (z. B. viele Agenturen und Start-ups) gibt der Auftraggeber die Linie vor.",
   "Dezentes Spiegeln funktioniert auch beim Stil. Schreibt der Kunde kurze Nachrichten, antworte kurz. Schreibt er ausführlich, darfst du etwas ausführlicher werden. Nutzt er Emojis, darfst du sparsam ein Emoji verwenden. In einer Verhandlungsstudie führte dezentes Anpassen an das Verhalten des Gegenübers zu besseren Ergebnissen für beide Seiten – auffälliges Kopieren wirkte dagegen negativ. Das Prinzip lautet: anpassen, nicht nachäffen.",
   "Am Telefon gelten zusätzliche Regeln. Lächeln hört man – zumindest wirkt die Stimme dann freundlicher. Sprich etwas langsamer als im Alltag, besonders bei Namen und Zahlen. Nutze Pausen: Nach einer Frage zu schweigen, fühlt sich anfangs unangenehm an, gibt dem Kunden aber Raum zum Nachdenken. Wer die Stille sofort füllt, beantwortet seine Frage am Ende selbst.",
   "Und wenn der Kunde unfreundlich wird? Bleib sachlich und freundlich, nimm es nicht persönlich und biete einen Ausweg an. „Ich merke, dass es gerade nicht passt – soll ich mich lieber gar nicht mehr melden?“ ist besser als jede schlagfertige Antwort. Wird jemand beleidigend, darfst du das Gespräch höflich beenden."
  ],["SRC-061","SRC-050"]),
  skill("Dezent spiegeln","psychologie","Länge, Tempo und Förmlichkeit der Nachrichten an den Kunden angleichen – ohne zu kopieren.",
   ["Länge der letzten Kundennachricht wahrnehmen.","Anrede und Förmlichkeit übernehmen (nie informeller als der Kunde).","Emojis höchstens sparsam und nur, wenn der Kunde selbst welche nutzt.","Einzelne Schlüsselwörter des Kunden aufgreifen."],
   "Ähnlichkeit im Stil schafft ein Gefühl von Verbundenheit und erleichtert das Gespräch.",
   "Maddux, Mullen & Galinsky (2008): Strategisches, dezentes Spiegeln verbesserte Verhandlungsergebnisse; offensichtliches Kopieren schadete.",
   "Kunde: „hi, was kostet sowas ca?“ → „Hi! Kommt stark aufs Dach an – magst du mir kurz sagen, wie groß es ungefähr ist?“ (sofern Du-Ansprache zum Auftraggeber passt)",
   "Spiegeln ist kein Mittel, um Nähe vorzutäuschen, die nicht da ist. Fachliche Klarheit und Ehrlichkeit gehen immer vor.",["SRC-061"]),
  check("Q-M02-013"),check("Q-M02-014"),check("Q-M02-015")
 ],
 "summary":["Kanal lesen, im Zweifel förmlicher beginnen.","Anrede spiegeln, nie informeller als der Kunde.","Länge und Stil dezent anpassen.","Telefon: langsam, Pausen aushalten, freundlich bleiben."]},

{"id":"M02-L06","title":"Vertrauen aufbauen","objectiveIds":["LO-M02-06"],"sourceIds":["SRC-059","SRC-050","SRC-038"],
 "blocks":[
  text("Worum es geht","Ohne Vertrauen gibt niemand ehrliche Antworten oder erscheint zu einem Termin. In dieser Lektion lernst du, woraus Vertrauen besteht und wie du es in wenigen Nachrichten aufbaust."),
  book("Kapitel 2.6","Die drei Säulen des Vertrauens",[
   "Ein bekanntes Modell aus der Organisationsforschung beschreibt Vertrauenswürdigkeit mit drei Säulen: Fähigkeit, Wohlwollen und Integrität. Fähigkeit heißt: Die Person weiß, wovon sie spricht. Wohlwollen heißt: Sie meint es gut mit mir. Integrität heißt: Sie hält sich an Regeln und an ihr Wort. Wer eine Säule verletzt, verliert Vertrauen – selbst wenn die anderen beiden stark sind.",
   "Fähigkeit zeigst du als Setter nicht, indem du alle Fachfragen beantwortest. Du zeigst sie durch gute Fragen, durch Verständnis des Problems und durch einen klaren Prozess. „Damit unser Berater Ihnen konkret sagen kann, was bei Ihrem Haus möglich ist, brauche ich drei Infos“ klingt kompetenter als jede auswendig gelernte Produktbeschreibung.",
   "Wohlwollen zeigst du, indem du die Interessen des Kunden über deine Terminquote stellst – und das auch sagst. „Ich möchte Ihnen keinen Termin verkaufen, der für Sie keinen Sinn ergibt“ ist kein Schwächezeichen, sondern einer der stärksten Vertrauenssätze überhaupt. Er wirkt aber nur, wenn er stimmt. Kunden merken sehr schnell, ob jemand ehrlich offen ist oder nur so tut.",
   "Integrität zeigst du durch kleine eingehaltene Versprechen. Wenn du schreibst „Ich melde mich bis 17 Uhr“, meldest du dich bis 17 Uhr. Wenn du sagst „Das dauert fünf Minuten“, dauert es fünf Minuten. Jedes eingehaltene Mini-Versprechen ist ein Beweis dafür, dass auch die großen Versprechen des Unternehmens stimmen könnten.",
   "Und Social Proof – also Hinweise auf andere zufriedene Kunden? Sie können Vertrauen stärken, wenn sie echt, konkret und mit Einwilligung genutzt werden („Wir haben in Ihrer Region dieses Jahr mehrere Altbauten mit Wärmepumpen ausgestattet“, sofern das stimmt). Erfundene Referenzen oder übertriebene Zahlen zerstören dagegen alle drei Säulen auf einmal – und sind obendrein wettbewerbswidrig."
  ],["SRC-059","SRC-038","SRC-050"]),
  skill("Das Mini-Versprechen","prozess","Kleine, überprüfbare Zusagen machen – und sie exakt einhalten.",
   ["Konkrete Zusage formulieren (Zeitpunkt, Inhalt).","Nur zusagen, was du sicher halten kannst.","Einhalten – am besten etwas früher.","Bei Verzögerung vorher Bescheid geben."],
   "Eingehaltene kleine Zusagen sind sichtbare Belege für Integrität.",
   "Vertrauensmodell Mayer, Davis & Schoorman (1995): Integrität als eigene Dimension der Vertrauenswürdigkeit. Konkrete Technik ist Praxiswissen.",
   "„Ich kläre mit unserem Berater, ob er auch samstags Termine anbietet, und melde mich bis heute 16 Uhr.“ – um 15:40 Uhr: „Wie versprochen: Samstag 10 Uhr wäre möglich.“",
   "Keine Zusagen im Namen anderer, die du nicht abgestimmt hast (z. B. Preise, Liefertermine).",["SRC-059"]),
  check("Q-M02-016"),check("Q-M02-017"),check("Q-M02-018"),
  {"kind":"reflect","prompt":"Denk an einen Verkäufer oder Kundenberater, dem du vertraut hast. Welche der drei Säulen hat er besonders gut gezeigt?"}
 ],
 "summary":["Vertrauen = Fähigkeit + Wohlwollen + Integrität.","Kompetenz durch gute Fragen und klaren Prozess zeigen.","Kundeninteresse ehrlich über die Terminquote stellen.","Mini-Versprechen halten; nur echten Social Proof nutzen."]},

{"id":"M02-L07","title":"Unterschiedliche Kundentypen – ohne Schubladen","objectiveIds":["LO-M02-07"],"sourceIds":["SRC-064","SRC-050"],
 "blocks":[
  text("Worum es geht","Manche Kunden wollen Fakten, andere Sicherheit, wieder andere Tempo. In dieser Lektion lernst du, dich auf das Verhalten im Gespräch einzustellen – ohne Menschen nach Persönlichkeitstests zu sortieren."),
  book("Kapitel 2.7","Verhalten lesen statt Typen raten",[
   "In vielen Vertriebstrainings werden Kunden in Farben oder Buchstaben eingeteilt: rot, gelb, grün, blau oder dominant, initiativ, stetig, gewissenhaft. Solche Modelle sind eingängig, aber wissenschaftlich schwach. Für bekannte Typentests wie den MBTI zeigen Studien zum Beispiel, dass viele Menschen bei einer Wiederholung nach einigen Wochen einen anderen Typ erhalten. Persönlichkeit ist kein Schubladensystem, sondern eher ein Spektrum – und sie zeigt sich in verschiedenen Situationen unterschiedlich.",
   "Was du stattdessen tun kannst: das aktuelle Verhalten im Gespräch lesen. Nicht „Der Kunde ist ein Analytiker“, sondern „Der Kunde stellt gerade viele Detailfragen“. Das ist beobachtbar, und du kannst direkt darauf reagieren. Fünf Muster begegnen dir besonders oft.",
   "Der Detailorientierte stellt viele genaue Fragen und will Zahlen. Gib ihm Struktur, nenne ehrlich, was du weißt und was nicht, und übergib Detailfragen schriftlich an den Berater. Der Eilige antwortet knapp und hat wenig Zeit. Komm auf den Punkt, frage nur das Nötigste und biete einen schnellen nächsten Schritt an. Der Unsichere zögert, schreibt „weiß nicht“ oder „mal schauen“. Gib ihm Sicherheit durch Transparenz: Was passiert im Termin? Was kostet ihn das (nichts)? Was passiert, wenn er danach Nein sagt (nichts)?",
   "Der Skeptische hat schlechte Erfahrungen gemacht oder misstraut Vertrieb generell. Erkläre offen deine Rolle, mach keine großen Versprechen und lass ihm die Kontrolle. Der Begeisterte will sofort loslegen. Freu dich mit ihm – und qualifiziere trotzdem sauber. Gerade begeisterte Kunden ohne Entscheidungsbefugnis oder Passung führen zu den enttäuschendsten Terminen.",
   "Wichtig ist der Effekt, den Psychologen „Barnum-Effekt“ nennen: Allgemeine Beschreibungen fühlen sich für fast jeden zutreffend an. Deshalb wirken Typenmodelle so überzeugend, auch wenn sie wenig vorhersagen. Nutze die fünf Muster als Werkzeugkasten für die aktuelle Situation – nicht als Etikett für einen Menschen."
  ],["SRC-064","SRC-050"]),
  {"kind":"caseStudy","title":"Fallstudie: Der Skeptiker","situation":"Herr Brandt (erfunden) schreibt: „Ehrlich gesagt hatte ich schon zwei Vertreter da, die mir das Blaue vom Himmel versprochen haben. Warum sollte das bei Ihnen anders sein?“","analysis":"Hier hilft keine Werbebotschaft. Erst das Gefühl benennen („Klingt, als hätten Sie keine guten Erfahrungen gemacht“), dann Transparenz über die eigene Rolle („Ich mache keine Angebote, ich kläre nur, ob ein Gespräch mit unserem Berater für Sie Sinn ergibt“) und Kontrolle zurückgeben („Wenn es nicht passt, sagen Sie es mir einfach – das ist völlig in Ordnung“). Keine Versprechen zu Ersparnissen oder Förderungen.","simulationNote":"Alle Daten in dieser Fallstudie sind erfunden."},
  skill("Verhalten spiegeln, nicht Typ etikettieren","gespraech","Auf das beobachtbare Verhalten in der letzten Nachricht reagieren.",
   ["Beobachten: Detailfragen? Kurze Antworten? Zögern? Misstrauen? Begeisterung?","Passende Reaktion wählen: Struktur, Tempo, Sicherheit, Transparenz oder saubere Qualifizierung.","Nach zwei, drei Nachrichten neu einschätzen – Menschen wechseln."],
   "Situatives Anpassen ist genauer und fairer als ein starres Etikett.",
   "Kritik an Typologien (Pittenger 2005 zum MBTI: geringe Retest-Reliabilität). Situative Anpassung ist Praxisheuristik (Expertenmeinung).",
   "Kunde schreibt nur „ok“ und „ja“. → Kurze Nachrichten, eine Frage, schneller nächster Schritt: „Passt Ihnen ein 20-Minuten-Gespräch am Donnerstag oder Freitag?“ (nach geklärten Kriterien)",
   "Keine Rückschlüsse auf Alter, Geschlecht, Herkunft oder Gesundheit. Du reagierst auf Verhalten, nicht auf Merkmale einer Person.",["SRC-064","SRC-050"]),
  myth("„Mit dem richtigen Persönlichkeitstest weißt du sofort, wie du jeden Kunden überzeugst.“",
   "Typentests haben oft geringe Zuverlässigkeit, und ihre allgemeinen Beschreibungen passen auf fast jeden (Barnum-Effekt). Verlässlicher ist es, das konkrete Verhalten im Gespräch zu beobachten und darauf einzugehen.",["SRC-064"]),
  check("Q-M02-019"),check("Q-M02-020"),check("Q-M02-021")
 ],
 "summary":["Typenmodelle sind eingängig, aber wissenschaftlich schwach.","Beobachtbares Verhalten lesen: detailorientiert, eilig, unsicher, skeptisch, begeistert.","Passend reagieren: Struktur, Tempo, Sicherheit, Transparenz, saubere Qualifizierung.","Keine Rückschlüsse auf persönliche Merkmale."]},
]
for l in lessons:
    l["moduleId"]="M02"; l["minutes"]=12

def q(id,obj,diff,typ,**kw):
    d={"id":id,"moduleId":"M02","objectiveId":obj,"difficulty":diff,"version":1,"type":typ}; d.update(kw); return d
S="SRC-050"
qs=[
q("Q-M02-001","LO-M02-01",1,"single",prompt="Welche Nachricht folgt am besten dem Prinzip „ein Gedanke pro Nachricht“?",
  options=[{"id":"a","text":"„Hallo Frau Lenz, danke für Ihre Anfrage! Was möchten Sie mit dem Speicher vor allem erreichen?“"},
           {"id":"b","text":"„Hallo, wir sind Marktführer, hier unser Katalog, wann haben Sie Zeit und wie groß ist Ihr Dach?“","misconception":"Mehrere Gedanken und Fragen auf einmal.","errorCategory":"kommunikationsfehler"},
           {"id":"c","text":"„Hallo.“","misconception":"Zu wenig: kein Bezug, keine Frage.","errorCategory":"kommunikationsfehler"},
           {"id":"d","text":"„Bitte füllen Sie das angehängte Formular mit 15 Fragen aus.“","misconception":"Wirkt wie Arbeit statt Gespräch.","errorCategory":"kommunikationsfehler"}],
  correct="a",explanation="Bezug + eine offene Frage am Ende: schnell zu lesen, leicht zu beantworten.",sourceIds=["SRC-066"]),
q("Q-M02-002","LO-M02-01",2,"errorspot",prompt="Markiere die Teile dieser Nachricht, die die Verständlichkeit verschlechtern.",
  lines=[{"id":"l1","text":"Hallo Herr Weber, danke für Ihre Anfrage!","faulty":False},
         {"id":"l2","text":"Wir prüfen Ihre JAZ und den SCOP Ihres Systems im Kontext der GEG-Vorgaben.","faulty":True,"why":"Unerklärte Fachbegriffe und Abkürzungen."},
         {"id":"l3","text":"Wie heizen Sie aktuell, wie alt ist die Anlage, wie groß ist das Haus und wann wollen Sie starten?","faulty":True,"why":"Vier Fragen auf einmal."},
         {"id":"l4","text":"Was ist Ihnen bei einer neuen Heizung am wichtigsten?","faulty":False}],
  explanation="Fachbegriffe ohne Erklärung und Mehrfachfragen machen Nachrichten schwer verständlich.",sourceIds=["SRC-066"]),
q("Q-M02-003","LO-M02-02",2,"single",prompt="Kunde: „Wir wollen vor allem unabhängiger vom Strompreis werden.“ Welche Antwort ist eine Paraphrase?",
  options=[{"id":"a","text":"„Also ist Ihnen Unabhängigkeit wichtiger als der schnelle Spareffekt – richtig?“"},
           {"id":"b","text":"„Dann brauchen Sie unseren Speicher XL.“","misconception":"Sofortige Lösung statt Verstehen.","errorCategory":"kommunikationsfehler"},
           {"id":"c","text":"„Okay.“","misconception":"Bloße Bestätigung zeigt kein Verständnis.","errorCategory":"kommunikationsfehler"},
           {"id":"d","text":"„Das sagen alle.“","misconception":"Abwertend und kein Zuhören.","errorCategory":"kommunikationsfehler"}],
  correct="a",explanation="Paraphrase = Kern in eigenen Worten, als Frage zur Bestätigung.",sourceIds=["SRC-055"]),
q("Q-M02-004","LO-M02-02",2,"situation",prompt="Wie reagierst du?",
  situation="Kundin: „Ich habe schon drei Angebote und blicke ehrlich gesagt gar nicht mehr durch.“",
  options=[{"id":"a","text":"„Klingt, als wären die Angebote gerade eher verwirrend als hilfreich. Was würde Ihnen am meisten helfen, Klarheit zu bekommen?“","quality":"best","feedback":"Lage benannt, Raum gegeben, offene Frage."},
           {"id":"b","text":"„Unser Angebot ist sowieso das beste.“","quality":"poor","feedback":"Ignoriert die Überforderung und wirkt wie Werbung.","errorCategory":"kommunikationsfehler"},
           {"id":"c","text":"„Okay, wann haben Sie Zeit für einen Termin?“","quality":"poor","feedback":"Themenwechsel statt Zuhören.","errorCategory":"kommunikationsfehler"},
           {"id":"d","text":"„Das verstehe ich. Wollen Sie, dass wir die Angebote im Termin gemeinsam einordnen?“","quality":"acceptable","feedback":"Zugewandt, springt aber etwas schnell zum Termin."}],
  explanation="Gefühle vorsichtig benennen, dann offen fragen – erst danach Lösungen.",sourceIds=["SRC-060","SRC-055"]),
q("Q-M02-005","LO-M02-02",2,"multi",prompt="Welche Reaktionen zeigen KEIN aktives Zuhören? (Mehrere Antworten möglich)",negation=True,
  options=[{"id":"a","text":"Sofort eine Produktempfehlung geben"},{"id":"b","text":"Das Thema wechseln"},
           {"id":"c","text":"Ein Wort des Kunden in einer Folgefrage aufgreifen","misconception":"Folgefragen sind ein Kernwerkzeug aktiven Zuhörens.","errorCategory":"kommunikationsfehler"},
           {"id":"d","text":"Ausführlich von eigenen Erfahrungen erzählen"},
           {"id":"e","text":"Den Kern zusammenfassen und bestätigen lassen","misconception":"Paraphrase ist aktives Zuhören.","errorCategory":"kommunikationsfehler"}],
  correct=["a","b","d"],explanation="Lösung, Themenwechsel und eigene Geschichten lenken vom Kunden weg.",sourceIds=["SRC-055","SRC-054"]),
q("Q-M02-006","LO-M02-03",2,"matching",prompt="Ordne jede Frage dem Fragetyp zu.",
  left=[{"id":"q1","text":"„Was hat Sie dazu gebracht, sich jetzt zu melden?“"},{"id":"q2","text":"„Sind Sie Eigentümer des Hauses?“"},
        {"id":"q3","text":"„Wie dringend ist das Thema, von 1 bis 10?“"},{"id":"q4","text":"„Was meinen Sie genau mit ‚zu teuer‘?“"}],
  right=[{"id":"open","text":"Offene Frage"},{"id":"closed","text":"Geschlossene Frage"},{"id":"scale","text":"Skalenfrage"},{"id":"clar","text":"Klärungsfrage"}],
  pairs={"q1":"open","q2":"closed","q3":"scale","q4":"clar"},explanation="Jeder Fragetyp hat eine eigene Aufgabe im Gespräch.",sourceIds=[S]),
q("Q-M02-007","LO-M02-03",2,"ordering",prompt="Bringe die Fragen in die Reihenfolge des Fragetrichters.",
  items=[{"id":"sum","text":"„Habe ich richtig verstanden, dass …?“"},{"id":"closed","text":"„Haben Sie bereits eine PV-Anlage?“"},
         {"id":"open","text":"„Was hat Sie dazu gebracht, sich zu melden?“"},{"id":"follow","text":"„Sie sagten, der Preis macht Ihnen Sorgen – wie hoch ist der Abschlag?“"}],
  correctOrder=["open","follow","closed","sum"],explanation="Breit beginnen, mit Folgefragen vertiefen, Pflichtkriterien klären, zusammenfassen.",sourceIds=[S]),
q("Q-M02-008","LO-M02-03",3,"single",prompt="Warum sind Implikationsfragen („Was passiert, wenn die Heizung im Winter ausfällt?“) im Erstkontakt eines Setters heikel?",
  options=[{"id":"a","text":"Sie können Ängste verstärken und wirken früh im Gespräch schnell manipulativ"},
           {"id":"b","text":"Sie sind gesetzlich verboten","misconception":"Kein Verbot – es ist eine Frage von Rolle und Ton.","errorCategory":"rechtsfehler"},
           {"id":"c","text":"Sie liefern nie Informationen","misconception":"Sie liefern Informationen, gehören aber eher ins Beratungsgespräch.","errorCategory":"ueberinterpretation"},
           {"id":"d","text":"Sie sind geschlossene Fragen","misconception":"Implikationsfragen sind meist offen.","errorCategory":"begriffsfehler"}],
  correct="a",explanation="SPIN-Implikationsfragen gehören eher ins Beratungsgespräch; im Erstkontakt sind Situation und Problem wichtiger.",sourceIds=["SRC-013"]),
q("Q-M02-009","LO-M02-03",2,"cloze",prompt="Ergänze die Lücken.",
  text="Beim Fragetrichter beginnst du {{g1}} und wirst dann immer {{g2}}. Statt „Warum haben Sie …?“ fragst du besser „{{g3}} hat dazu geführt …?“",
  gaps=[{"id":"g1","accepted":["breit","offen","allgemein"]},{"id":"g2","accepted":["konkreter","enger","spezifischer"]},{"id":"g3","accepted":["Was"]}],
  explanation="Breit → konkret; „Was hat dazu geführt“ klingt neugierig statt vorwurfsvoll.",sourceIds=[S]),
q("Q-M02-010","LO-M02-04",2,"ordering",prompt="Bringe die Teile der 4-Satz-Telefoneröffnung in die richtige Reihenfolge.",
  items=[{"id":"pause","text":"Pause – warten"},{"id":"ask","text":"Dauer nennen und fragen, ob es passt"},{"id":"name","text":"Name und Unternehmen"},{"id":"ref","text":"Bezug zur Anfrage"}],
  correctOrder=["name","ref","ask","pause"],explanation="Wer – warum – wie lange/darf ich – Pause.",sourceIds=["SRC-058","SRC-052"]),
q("Q-M02-011","LO-M02-04",2,"truefalse",prompt="Die 7-38-55-Regel von Mehrabian beweist, dass Worte in jedem Verkaufsgespräch nur 7 % der Wirkung ausmachen.",
  correct=False,errorCategory="ueberinterpretation",explanation="Die Regel stammt aus Experimenten zu widersprüchlichen Gefühlsbotschaften; Mehrabian selbst warnt vor der Verallgemeinerung.",sourceIds=["SRC-063"]),
q("Q-M02-012","LO-M02-04",3,"situation",prompt="Was antwortest du?",
  situation="Am Telefon (Kunde hat angefragt) sagt der Kunde nach deiner Eröffnung: „Gerade schlecht, ich sitze im Auto.“",
  options=[{"id":"a","text":"„Kein Problem! Wann passt es Ihnen besser – heute Abend oder morgen Vormittag?“","quality":"best","feedback":"Respektiert die Situation und sichert einen konkreten neuen Zeitpunkt."},
           {"id":"b","text":"„Es dauert wirklich nur zwei Minuten …“","quality":"poor","feedback":"Ignoriert die klare Aussage und gefährdet ihn im Straßenverkehr.","errorCategory":"ethikfehler"},
           {"id":"c","text":"„Okay, tschüss.“","quality":"acceptable","feedback":"Respektvoll, aber ohne neuen Zeitpunkt."},
           {"id":"d","text":"„Dann fasse ich schnell zusammen, was wir anbieten …“","quality":"unacceptable","feedback":"Redet über ein ausdrückliches „gerade schlecht“ hinweg.","errorCategory":"ethikfehler"}],
  explanation="Die Erlaubnisfrage liefert Information: Jetzt passt es nicht – also einen besseren Zeitpunkt finden.",sourceIds=["SRC-052",S]),
q("Q-M02-013","LO-M02-05",2,"single",prompt="Ein Interessent schreibt dir auf Instagram: „hey, macht ihr auch logos?“ Wie antwortest du (die Agentur hat Du-Kultur)?",
  options=[{"id":"a","text":"„Hey! Ja, machen wir. Wofür brauchst du das Logo – neues Projekt oder Auffrischung?“"},
           {"id":"b","text":"„Sehr geehrter Herr, bezugnehmend auf Ihre Anfrage teilen wir Ihnen mit …“","misconception":"Viel zu förmlich für Kanal und Ton des Kunden.","errorCategory":"kommunikationsfehler"},
           {"id":"c","text":"„jo klar 🔥🔥🔥 call?“","misconception":"Übertriebenes Spiegeln, unprofessionell, springt ohne Bedarf zum Termin.","errorCategory":"kommunikationsfehler"},
           {"id":"d","text":"Keine Antwort, weil keine Großschreibung verwendet wurde","misconception":"Stil ist kein Qualifizierungskriterium.","errorCategory":"qualifizierungsfehler"}],
  correct="a",explanation="Kanal und Anrede spiegeln, kurz bleiben, mit einer offenen Frage starten.",sourceIds=["SRC-061"]),
q("Q-M02-014","LO-M02-05",2,"multi",prompt="Welche Telefon-Regeln stimmen? (Mehrere Antworten möglich)",
  options=[{"id":"a","text":"Bei Namen und Zahlen langsamer sprechen"},{"id":"b","text":"Nach einer Frage eine Pause aushalten"},
           {"id":"c","text":"Jede Stille sofort mit eigenen Worten füllen","misconception":"Wer die Stille füllt, beantwortet seine Frage oft selbst.","errorCategory":"kommunikationsfehler"},
           {"id":"d","text":"Bei Beleidigungen das Gespräch höflich beenden dürfen"},
           {"id":"e","text":"Möglichst schnell sprechen, um Zeit zu sparen","misconception":"Schnelles Sprechen wirkt nervös und callcenterhaft.","errorCategory":"kommunikationsfehler"}],
  correct=["a","b","d"],explanation="Langsam, mit Pausen, freundlich – und mit klaren Grenzen bei Beleidigungen.",sourceIds=[S]),
q("Q-M02-015","LO-M02-05",3,"truefalse",prompt="Laut Verhandlungsforschung wirkt auffälliges, offensichtliches Kopieren des Gegenübers genauso gut wie dezentes Anpassen.",
  correct=False,errorCategory="ueberinterpretation",explanation="Maddux et al. (2008): Dezentes Spiegeln half, offensichtliches Kopieren schadete.",sourceIds=["SRC-061"]),
q("Q-M02-016","LO-M02-06",2,"matching",prompt="Ordne jedes Verhalten der Vertrauenssäule zu, die es vor allem stärkt.",
  left=[{"id":"b1","text":"Gezielte Fragen stellen und den Prozess erklären"},{"id":"b2","text":"„Ich möchte Ihnen keinen Termin verkaufen, der für Sie keinen Sinn ergibt.“"},{"id":"b3","text":"Eine Rückmeldung bis 16 Uhr zusagen und einhalten"}],
  right=[{"id":"ability","text":"Fähigkeit"},{"id":"benev","text":"Wohlwollen"},{"id":"integr","text":"Integrität"}],
  pairs={"b1":"ability","b2":"benev","b3":"integr"},explanation="Vertrauensmodell nach Mayer, Davis & Schoorman (1995).",sourceIds=["SRC-059"]),
q("Q-M02-017","LO-M02-06",2,"single",prompt="Welcher Hinweis auf andere Kunden ist zulässig?",
  options=[{"id":"a","text":"Ein wahrer, konkreter Hinweis, den der Auftraggeber freigegeben hat"},
           {"id":"b","text":"„Alle Ihre Nachbarn haben schon gebucht“ – ohne zu wissen, ob es stimmt","misconception":"Erfundener Social Proof ist Täuschung.","errorCategory":"ethikfehler"},
           {"id":"c","text":"Eine erfundene Kundenbewertung mit Foto","misconception":"Gefälschte Bewertungen sind unzulässig.","errorCategory":"rechtsfehler"},
           {"id":"d","text":"„Über 10.000 zufriedene Kunden“ als Schätzung","misconception":"Unbelegte Zahl.","errorCategory":"ethikfehler"}],
  correct="a",explanation="Social Proof nur, wenn er wahr, konkret und freigegeben ist.",sourceIds=["SRC-038",S]),
q("Q-M02-018","LO-M02-06",2,"situation",prompt="Wie reagierst du?",
  situation="Du hast „Ich melde mich bis 17 Uhr“ geschrieben. Um 16:45 Uhr hast du die Info vom Berater noch nicht.",
  options=[{"id":"a","text":"Vor 17 Uhr kurz melden: „Ich warte noch auf die Antwort unseres Beraters und melde mich morgen bis 10 Uhr.“","quality":"best","feedback":"Integrität: Versprechen nicht stillschweigend brechen."},
           {"id":"b","text":"Nichts schreiben und morgen antworten","quality":"poor","feedback":"Gebrochenes Mini-Versprechen beschädigt Vertrauen.","errorCategory":"prozessfehler"},
           {"id":"c","text":"Eine Antwort erfinden, damit die Frist gehalten wird","quality":"unacceptable","feedback":"Falschinformation – schlimmer als jede Verspätung.","errorCategory":"ethikfehler"},
           {"id":"d","text":"Um 18 Uhr schreiben, dass du viel zu tun hattest","quality":"acceptable","feedback":"Ehrlich, aber zu spät."}],
  explanation="Wenn du ein Versprechen nicht halten kannst, sag es vorher.",sourceIds=["SRC-059"]),
q("Q-M02-019","LO-M02-07",2,"matching",prompt="Ordne jedem beobachteten Verhalten eine passende Reaktion zu.",
  left=[{"id":"v1","text":"Viele genaue Detailfragen"},{"id":"v2","text":"Sehr knappe Antworten, wenig Zeit"},{"id":"v3","text":"„Weiß nicht … mal schauen“"},{"id":"v4","text":"„Vertreter versprechen immer viel“"}],
  right=[{"id":"r1","text":"Struktur geben, Detailfragen an Berater übergeben"},{"id":"r2","text":"Auf den Punkt, nur das Nötigste fragen"},{"id":"r3","text":"Sicherheit durch Transparenz über den nächsten Schritt"},{"id":"r4","text":"Rolle offenlegen, keine großen Versprechen, Kontrolle lassen"}],
  pairs={"v1":"r1","v2":"r2","v3":"r3","v4":"r4"},explanation="Auf Verhalten reagieren, nicht auf ein Typen-Etikett.",sourceIds=[S]),
q("Q-M02-020","LO-M02-07",3,"single",prompt="Warum wirken Persönlichkeitstypen-Beschreibungen oft so zutreffend, obwohl sie wenig vorhersagen?",
  options=[{"id":"a","text":"Wegen des Barnum-Effekts: Allgemeine Beschreibungen fühlen sich für fast jeden passend an"},
           {"id":"b","text":"Weil sie neurologisch gemessen werden","misconception":"Typentests sind Fragebögen, keine neurologischen Messungen.","errorCategory":"ueberinterpretation"},
           {"id":"c","text":"Weil Menschen ihren Typ nie ändern","misconception":"Gerade die Retest-Stabilität ist oft gering.","errorCategory":"ueberinterpretation"},
           {"id":"d","text":"Weil sie gesetzlich zertifiziert sind","misconception":"Es gibt keine solche Zertifizierung.","errorCategory":"begriffsfehler"}],
  correct="a",explanation="Barnum-Effekt plus geringe Retest-Reliabilität (z. B. MBTI, Pittenger 2005).",sourceIds=["SRC-064"]),
q("Q-M02-021","LO-M02-07",2,"situation",prompt="Was ist der beste nächste Schritt?",
  situation="Ein Kunde ist begeistert: „Super, ich will das unbedingt, wann können Sie kommen?“ Du weißt noch nicht, ob er Eigentümer ist.",
  options=[{"id":"a","text":"Freude teilen und vor dem Termin kurz die Eigentumsfrage klären","quality":"best","feedback":"Begeisterung ernst nehmen – und trotzdem sauber qualifizieren."},
           {"id":"b","text":"Sofort einen Termin eintragen","quality":"poor","feedback":"Begeisterung ersetzt keine Qualifizierung.","errorCategory":"qualifizierungsfehler"},
           {"id":"c","text":"Die Begeisterung bremsen: „Langsam, das ist teuer.“","quality":"poor","feedback":"Unnötig negativ, keine Qualifizierung.","errorCategory":"kommunikationsfehler"},
           {"id":"d","text":"Ihm sagen, er solle erst drei andere Angebote einholen","quality":"acceptable","feedback":"Nicht falsch, aber nicht deine Aufgabe und ohne Qualifizierung."}],
  explanation="Gerade begeisterte Kunden ohne Passung führen zu enttäuschenden Terminen.",sourceIds=[S]),
q("Q-M02-022","LO-M02-01",2,"freetext",prompt="Kürze diese Nachricht auf höchstens 30 Wörter mit genau einer Frage: „Hallo Herr Demir, vielen herzlichen Dank für Ihre Anfrage zu unseren Recruiting-Dienstleistungen, wir sind ein erfahrenes Team und unterstützen Unternehmen seit Jahren bei der Personalsuche. Wie viele Stellen haben Sie offen, in welchen Bereichen, wie schnell müssen sie besetzt werden und wer entscheidet bei Ihnen?“",
  rubric=[{"id":"c1","description":"Spricht Herrn Demir mit Namen an","points":1,"anyOf":[["demir"]]},
          {"id":"c2","description":"Bezug zur Anfrage","points":1,"anyOf":[["anfrage","recruiting","personal","stelle"]]},
          {"id":"c3","description":"Enthält eine offene Frage","points":1,"anyOf":[["was ","welche","wie "]]},
          {"id":"c4","description":"Keine Werbefloskel wie „erfahrenes Team“ oder „seit Jahren“","points":1,"forbidden":["erfahrenes team","seit jahren","marktführer"]}],
  sampleAnswer="Hallo Herr Demir, danke für Ihre Anfrage zum Recruiting! Welche Stelle ist für Sie gerade am dringendsten?",
  requiresManualReview=True,explanation="Kurz, persönlich, eine Frage. Die Wortzahl prüfst du selbst – der Selbstcheck erkennt nur Muster.",sourceIds=["SRC-066"]),
q("Q-M02-023","LO-M02-02",3,"freetext",prompt="Kunde: „Wir hatten letztes Jahr schon mal eine Agentur, das war rausgeschmissenes Geld.“ Schreibe eine Antwort, die das Gefühl benennt und mit einer offenen Frage endet.",
  rubric=[{"id":"c1","description":"Benennt das Gefühl/die Erfahrung vorsichtig","points":1,"anyOf":[["klingt","wirkt","verstehe","nachvollziehbar","frustr","enttäusch","ärger"]]},
          {"id":"c2","description":"Endet mit einer offenen Frage","points":1,"anyOf":[["was ","wie ","welche","woran"]]},
          {"id":"c3","description":"Keine Rechtfertigung oder Abwertung der anderen Agentur","points":1,"forbidden":["wir sind besser","die anderen","unseriös","bei uns passiert das nicht"]}],
  sampleAnswer="Klingt, als hätten Sie mit der letzten Agentur keine guten Erfahrungen gemacht. Was lief damals nicht so, wie Sie es sich vorgestellt hatten?",
  requiresManualReview=True,explanation="Erst verstehen, dann (viel später) über Lösungen sprechen. Andere Anbieter schlechtzumachen schadet dem Vertrauen.",sourceIds=["SRC-060","SRC-055"]),
q("Q-M02-024","LO-M02-03",2,"situation",prompt="Welche Frage stellst du?",
  situation="Kunde: „Das ist mir alles zu teuer.“ Du weißt nicht, worauf sich „teuer“ bezieht.",
  options=[{"id":"a","text":"„Was meinen Sie genau mit ‚zu teuer‘ – den Gesamtpreis oder die monatliche Belastung?“","quality":"best","feedback":"Klärungsfrage verhindert ein Missverständnis."},
           {"id":"b","text":"„Wir können sicher einen Rabatt machen!“","quality":"unacceptable","feedback":"Ungeprüfte Preiszusage außerhalb deiner Rolle.","errorCategory":"rollenverwechslung"},
           {"id":"c","text":"„Qualität hat eben ihren Preis.“","quality":"poor","feedback":"Floskel ohne Verständnis.","errorCategory":"kommunikationsfehler"},
           {"id":"d","text":"„Warum denken Sie das?“","quality":"acceptable","feedback":"Frage ist okay, klingt aber eher wie ein Vorwurf."}],
  explanation="Erst klären, was gemeint ist – dann entscheiden, ob es eine Frage für den Berater ist.",sourceIds=[S]),
q("Q-M02-025","LO-M02-06",3,"truefalse",prompt="Der Satz „Ich möchte Ihnen keinen Termin verkaufen, der für Sie keinen Sinn ergibt“ stärkt Vertrauen nur dann, wenn er auch ernst gemeint ist und du entsprechend handelst.",
  correct=True,errorCategory="ethikfehler",explanation="Wohlwollen muss sich im Verhalten zeigen – sonst wirkt der Satz als Masche.",sourceIds=["SRC-059"]),
q("Q-M02-026","LO-M02-04",2,"single",prompt="Der Kunde sagt auf deine Erlaubnisfrage „Passt es gerade?“: „Nein.“ Was hast du gewonnen?",
  options=[{"id":"a","text":"Eine wertvolle Information – jetzt einen besseren Zeitpunkt vereinbaren"},
           {"id":"b","text":"Nichts – die Erlaubnisfrage war ein Fehler","misconception":"Ein Gespräch gegen den Willen bringt nichts.","errorCategory":"kommunikationsfehler"},
           {"id":"c","text":"Das Recht, trotzdem kurz alles zu erklären","misconception":"Das ignoriert die Antwort.","errorCategory":"ethikfehler"},
           {"id":"d","text":"Einen Grund, den Lead zu löschen","misconception":"„Jetzt nicht“ ist kein „nie“.","errorCategory":"qualifizierungsfehler"}],
  correct="a",explanation="Ein Nein zum Zeitpunkt ist kein Nein zum Thema.",sourceIds=["SRC-052"]),
q("Q-M02-027","LO-M02-05",2,"single",prompt="Ein Kunde wird unfreundlich: „Ihr nervt, ständig diese Nachrichten!“ Was ist die beste Antwort?",
  options=[{"id":"a","text":"„Das tut mir leid. Soll ich Sie aus unseren Nachrichten austragen? Dann melden wir uns nicht mehr.“"},
           {"id":"b","text":"„Sie haben sich doch selbst angemeldet!“","misconception":"Rechtfertigung eskaliert.","errorCategory":"kommunikationsfehler"},
           {"id":"c","text":"Ihn ignorieren und nächste Woche wieder schreiben","misconception":"Widerspruch muss beachtet werden.","errorCategory":"rechtsfehler"},
           {"id":"d","text":"„Nur noch eine letzte Nachricht mit unserem Angebot …“","misconception":"Weitere Werbung trotz Ablehnung.","errorCategory":"ethikfehler"}],
  correct="a",explanation="Freundlich bleiben, einen Ausweg anbieten und den Wunsch umsetzen.",sourceIds=["SRC-019",S]),
q("Q-M02-028","LO-M02-07",2,"truefalse",prompt="Aus dem Alter oder der Herkunft eines Kunden kann ein Setter ableiten, welche Gesprächstechnik am besten funktioniert.",
  correct=False,errorCategory="ethikfehler",explanation="Du reagierst auf beobachtbares Verhalten im Gespräch, nicht auf persönliche Merkmale – alles andere ist Vorurteil.",sourceIds=["SRC-064",S]),
]
mod={"id":"M02","number":2,"title":"Professionelle Kommunikation","subtitle":"Klar schreiben, sichtbar zuhören, gezielt fragen, Vertrauen aufbauen.",
 "status":"verfuegbar","prerequisites":["M01"],"version":"1.0.0","passThreshold":0.8,
 "sourceIds":sorted({s for l in lessons for s in l["sourceIds"]}|{"SRC-050"}),
 "objectives":[{"id":i,"moduleId":"M02","text":t,"bloom":b} for i,t,b in O],
 "lessons":lessons,
 "transferTask":{"title":"Transferaufgabe: Dein Gesprächsprotokoll","instructions":"Führe ein echtes Alltagsgespräch (Familie, Freunde, Kollegen – kein Verkauf) und wende bewusst an: eine Paraphrase, ein benanntes Gefühl, zwei Folgefragen. Schreibe danach auf (ohne Namen oder private Details): Was hast du gesagt? Wie hat die Person reagiert? Was würdest du nächstes Mal anders machen? Schreibe zusätzlich drei Chat-Eröffnungen für drei Kanäle (WhatsApp B2C, Instagram B2B mit Du-Kultur, E-Mail B2B mit Sie).",
   "criteria":["Paraphrase ist als Frage formuliert","Gefühl wurde vorsichtig benannt, nicht diagnostiziert","Folgefragen greifen konkrete Wörter auf","Reflexion benennt eine konkrete Verbesserung","Drei Eröffnungen passen zu Kanal und Anrede","Jede Eröffnung enthält Bezug und genau eine Frage","Keine echten Namen oder privaten Details"]},
 "examQuestionIds":["Q-M02-001","Q-M02-005","Q-M02-006","Q-M02-008","Q-M02-011","Q-M02-013","Q-M02-014","Q-M02-015","Q-M02-016","Q-M02-017","Q-M02-020","Q-M02-024","Q-M02-025","Q-M02-026","Q-M02-027","Q-M02-028"]}
json.dump(mod,open('content/modules/M02.json','w'),ensure_ascii=False,indent=2)
json.dump(qs,open('content/questions/M02.json','w'),ensure_ascii=False,indent=2)
print(len(qs))
