"""Manual root-cause labels for the UNCERTAIN cases of golden v1/v2 (state at commit 2365ca7 + de-memorisation).

Analysis only: labels describe WHY the engine could not decide - they are never used by the engine.
Categories (primary cause per question):
"""

CATEGORIES = {
    "CONTRARY_NOT_DERIVABLE": ("Die richtige Option wird gefunden, die falschen Optionen lassen sich aber nicht "
                               "widerlegen, weil keine Regel die abweichende Handlung ausdrücklich verbietet",
                               "Handlungs-Konzepte mit Unverträglichkeiten (WARTEN vs. WEITERFAHREN, ANHALTEN vs. "
                               "DURCHROLLEN …): eine Option, die der von der Regel verlangten Handlung in derselben "
                               "Situation widerspricht, ist FALSCH"),
    "PARAPHRASE_MISMATCH": ("Regel vorhanden, die Antwort sagt dasselbe mit anderen Worten/Satzbau",
                            "semantische Normalisierung (Konzepte statt Wörter), Handlungs-/Objekt-Konzepte"),
    "YES_NO_PROPOSITION": ("Ja/Nein-Frage; die Aussage steckt in der Frage, die Antwort ist nur 'Ja'/'Nein'",
                           "Frage in eine Proposition umbauen (Modalverb + Prädikat) und strukturell prüfen"),
    "ANSWER_REFERENCE_UNKNOWN": ("Kurzantwort verweist auf eine Rolle der Frage ('Ich', 'Der Gegenverkehr', "
                                 "'Rechts', 'Die gelben')", "Antwort-Rollen auflösen: Sprecher/Akteur/Gegenüber "
                                 "aus der Frage übernehmen"),
    "NUMERIC_CONTEXT": ("Zahl hängt an einer Bedingung der Frage (Fahrzeug, Sicht, Ort) oder an einer anderen "
                        "Größe/Einheit; die Zahlenregel wird nicht der Frage zugeordnet",
                        "Bedingungs-Extraktion (Fahrzeug, Sicht, Ort, Größe) + Zahlenregeln strukturell "
                        "abrufen (quantity, applies_to)"),
    "SIGN_NAME_MATCH": ("'Was bedeutet Zeichen X?' mit dem amtlichen Namen als Antwort wird nicht sicher "
                        "zugeordnet", "Zeichen-Antworten zuerst gegen die amtlichen Namen aller Zeichen prüfen"),
    "QUESTION_TYPE_UNKNOWN": ("Fragetyp nicht erkannt ('Was ist untersagt?', 'Ab wann …?', 'Welche Aussage "
                              "ist falsch?' ohne Kontext)", "Intent-Erkennung (PROHIBITION, PERMISSION, "
                              "REQUIRED_ACTION …) und Antwort im Licht des Intents lesen"),
    "CONDITION_EXTRACTION": ("Bedingungen der Frage (Alter, Größe, 'ohne', 'ausgefallen') werden nicht "
                             "strukturiert und nicht mit den Regelbedingungen verglichen",
                             "Bedingungs-Rahmen (Akteur, Fahrzeug, Ort, Wetter, Zustand, Ausnahme) aus der Frage"),
    "COMPOSITE_RULE": ("Antwort braucht mehrere Regeln oder eine Folgerung aus einer Regel "
                       "(z. B. 'rechten Blinker setzen' widerspricht 'nicht blinken')",
                       "Regel-Komposition + Ableitungen über Konzepte"),
    "SOURCE_UNVERIFIED": ("Regel nur aus nicht verifizierbarer Quelle (FeV/StVG)", "amtliche Quelle beschaffen"),
    "MISSING_RULE": ("Die nötige Regel/Aussage fehlt in der Wissensbasis", "Wissen aus belastbarer Quelle ergänzen"),
}

# id -> (primary, [secondary...], own short description of the case)
LABELS = {
    "G002": ("NUMERIC_CONTEXT", ["CONDITION_EXTRACTION"], "Pkw mit Wohnanhänger außerorts - Anhänger-Tempo wird nicht eindeutig der Frage zugeordnet"),
    "G008": ("PARAPHRASE_MISMATCH", ["CONTRARY_NOT_DERIVABLE"], "spielende Kinder: 'langsamer und bremsbereit' anders formuliert als die Regel"),
    "G009": ("NUMERIC_CONTEXT", [], "Faustregel-Abstand bei 100 km/h - die Rechenregel wird nicht erkannt, Seitenabstand-Zahlen gewinnen"),
    "G010": ("ANSWER_REFERENCE_UNKNOWN", [], "rechts vor links - Antwort nennt nur 'den Pkw von rechts'"),
    "G011": ("PARAPHRASE_MISMATCH", ["CONDITION_EXTRACTION"], "aus Waldweg einbiegen - 'durchfahren lassen' statt 'Vorfahrt gewähren'"),
    "G012": ("COMPOSITE_RULE", ["CONTRARY_NOT_DERIVABLE"], "Kreisverkehr: 'rechten Blinker beim Einfahren' widerspricht 'nicht blinken'"),
    "G014": ("CONTRARY_NOT_DERIVABLE", [], "Polizei Arme quer - 'ich darf fahren' widerspricht 'Halt'"),
    "G015": ("PARAPHRASE_MISMATCH", [], "Polizei vor Ampel - 'anhalten' statt 'Haltezeichen befolgen'"),
    "G016": ("CONTRARY_NOT_DERIVABLE", ["PARAPHRASE_MISMATCH"], "Einsatzfahrzeug - 'normal weiterfahren', 'auf Vorfahrt bestehen' widersprechen 'freie Bahn schaffen'"),
    "G017": ("PARAPHRASE_MISMATCH", ["COMPOSITE_RULE"], "Grünpfeil - 'zuerst anhalten', Fußgänger nicht behindern"),
    "G021": ("CONTRARY_NOT_DERIVABLE", [], "Bahnübergang Stau - 'auf den Übergang fahren' widerspricht 'vor dem Andreaskreuz warten'"),
    "G022": ("CONTRARY_NOT_DERIVABLE", [], "Bus mit Warnblinklicht, Gegenverkehr - 'unvermindert' widerspricht 'Schrittgeschwindigkeit'"),
    "G023": ("PARAPHRASE_MISMATCH", [], "Grundstücksausfahrt - 'Gefährdung ausschließen' wörtlich anders"),
    "G024": ("CONTRARY_NOT_DERIVABLE", [], "Stau hinter Kreuzung - 'einfahren, weil Grün' widerspricht der Regel"),
    "G026": ("SIGN_NAME_MATCH", [], "Zeichen 306 - amtlicher Name als Antwort"),
    "G027": ("SIGN_NAME_MATCH", [], "Zeichen 206 - amtlicher Name als Antwort"),
    "G028": ("PARAPHRASE_MISMATCH", ["CONTRARY_NOT_DERIVABLE"], "Stoppschild bei freier Straße - 'trotzdem anhalten'"),
    "G029": ("SIGN_NAME_MATCH", ["PARAPHRASE_MISMATCH"], "Tempo-30-Zone - Bedeutung umschrieben"),
    "G030": ("CONTRARY_NOT_DERIVABLE", [], "verkehrsberuhigter Bereich - 'überall parken' widerspricht 'nur auf gekennzeichneten Flächen'"),
    "G031": ("NUMERIC_CONTEXT", ["COMPOSITE_RULE"], "eingeschränktes Haltverbot - Aussteigen erlaubt, '10 Minuten parken' nicht"),
    "G032": ("CONTRARY_NOT_DERIVABLE", [], "absolutes Haltverbot - 'kurz halten zum Aussteigen' widerspricht 'Halten verboten'"),
    "G033": ("PARAPHRASE_MISMATCH", [], "Zeichen 276 - 'mehrspurige Kfz dürfen nicht überholt werden' anders formuliert"),
    "G034": ("ANSWER_REFERENCE_UNKNOWN", [], "gelbe vs. weiße Markierung - Antworten 'Die gelben'/'Die weißen'"),
    "G036": ("NUMERIC_CONTEXT", [], "einstreifige Bake - Zahl hängt am Bakentyp"),
    "G037": ("CONTRARY_NOT_DERIVABLE", [], "durchgezogene Linie - 'zum Überholen kurz überfahren' widerspricht"),
    "G038": ("PARAPHRASE_MISMATCH", [], "Überholvoraussetzung umformuliert"),
    "G039": ("QUESTION_TYPE_UNKNOWN", ["CONTRARY_NOT_DERIVABLE"], "'Was ist untersagt?' - Antwort ist eine Handlung ohne Modalverb"),
    "G042": ("PARAPHRASE_MISMATCH", ["CONTRARY_NOT_DERIVABLE"], "Reißverschluss - Kurzantwort ohne Verb"),
    "G043": ("CONTRARY_NOT_DERIVABLE", [], "Ausfahrt verpasst - 'wenden' widerspricht Wendeverbot"),
    "G046": ("YES_NO_PROPOSITION", [], "Hupen innerorts zum Überholen - 'Nein, nur außerorts'"),
    "G047": ("QUESTION_TYPE_UNKNOWN", ["NUMERIC_CONTEXT"], "'Ab wann parken Sie?' - Antwort als Bedingung"),
    "G048": ("NUMERIC_CONTEXT", ["CONDITION_EXTRACTION"], "Parkverbot vor Kreuzung (ohne Radweg) - 5 m vs. 8 m"),
    "G049": ("NUMERIC_CONTEXT", [], "Haltestelle 15 m - richtige Zahl, aber keine Auswahl"),
    "G051": ("NUMERIC_CONTEXT", ["CONTRARY_NOT_DERIVABLE"], "Anhänger parken - 'drei Tage' in anderer Einheit als 'zwei Wochen'"),
    "G052": ("CONTRARY_NOT_DERIVABLE", [], "Panne - 'Warndreieck direkt hinter das Fahrzeug' widerspricht '100 m'"),
    "G055": ("PARAPHRASE_MISMATCH", [], "Unfall mit parkendem Auto - Wartepflicht umformuliert"),
    "G056": ("PARAPHRASE_MISMATCH", ["CONTRARY_NOT_DERIVABLE"], "Abschleppen auf der Autobahn umformuliert"),
    "G058": ("CONTRARY_NOT_DERIVABLE", [], "Nebelschlussleuchte - 'bei Dunkelheit' ist nicht der zulässige Fall"),
    "G060": ("PARAPHRASE_MISMATCH", [], "Ladung 1,2 m - 'Ladungsende kenntlich machen'"),
    "G061": ("YES_NO_PROPOSITION", [], "Handy bei Start-Stopp - 'Nein'"),
    "G064": ("CONDITION_EXTRACTION", ["COMPOSITE_RULE"], "Kind 7 Jahre - Alter < 8 muss mit der Regel verglichen werden"),
    "G067": ("CONDITION_EXTRACTION", ["PARAPHRASE_MISMATCH"], "Kind 10 Jahre, 140 cm - Bedingungen der Kindersitzpflicht"),
    "G068": ("YES_NO_PROPOSITION", [], "Radwegbenutzung ohne Schild - 'Ja, jeder Radweg' nicht widerlegt"),
    "G069": ("YES_NO_PROPOSITION", ["NUMERIC_CONTEXT"], "Mofa 25 km/h auf Autobahn - 'Nein'"),
    "G070": ("PARAPHRASE_MISMATCH", [], "mittlerer Fahrstreifen - 'Einordnen zum Linksabbiegen'"),
    "G071": ("SOURCE_UNVERIFIED", [], "Klasse B mit 750-kg-Anhänger (FeV)"),
    "G072": ("SOURCE_UNVERIFIED", [], "Probezeit (StVG)"),
    "G073": ("SOURCE_UNVERIFIED", ["PARAPHRASE_MISMATCH"], "Alkoholabbau"),
    "G074": ("CONTRARY_NOT_DERIVABLE", [], "Müdigkeit - 'Fenster auf, Musik, weiter' widerspricht 'Pause'"),
    "G075": ("QUESTION_TYPE_UNKNOWN", [], "'Was ist NICHT erlaubt?' beim Linksabbiegen"),
    "G076": ("QUESTION_TYPE_UNKNOWN", ["PARAPHRASE_MISMATCH"], "'Welche Aussage ist falsch?' ohne Situationskontext"),
    "G078": ("CONTRARY_NOT_DERIVABLE", [], "Winterreifen - 'Antriebsachse genügt' widerspricht 'alle Räder'"),
    "G079": ("ANSWER_REFERENCE_UNKNOWN", [], "Hindernis auf meiner Seite - Antworten 'Ich'/'Der Gegenverkehr'"),
    "G080": ("SIGN_NAME_MATCH", [], "Zeichen 301 - Bedeutung als Antwort"),
    "H002": ("NUMERIC_CONTEXT", ["CONDITION_EXTRACTION"], "Schneefall, 30 m Sicht - Sicht-Bedingung nicht extrahiert"),
    "H005": ("NUMERIC_CONTEXT", [], "Bremsweg bei verdreifachter Geschwindigkeit (mit konkreten Zahlen im Text)"),
    "H006": ("CONTRARY_NOT_DERIVABLE", [], "angepasste Geschwindigkeit - 'so schnell wie das Schild erlaubt' widerspricht"),
    "H007": ("NUMERIC_CONTEXT", ["CONDITION_EXTRACTION"], "Lkw über 3,5 t auf Autobahn - Mindestabstand"),
    "H008": ("PARAPHRASE_MISMATCH", [], "ältere Fußgängerin - 'mit Fehlverhalten rechnen'"),
    "H009": ("PARAPHRASE_MISMATCH", ["ANSWER_REFERENCE_UNKNOWN"], "Radfahrer von rechts - 'der Radfahrer hat Vorfahrt'"),
    "H010": ("PARAPHRASE_MISMATCH", ["CONTRARY_NOT_DERIVABLE"], "Rechtsabbiegen, Radfahrerin geradeaus - 'zuerst durchfahren lassen'"),
    "H011": ("ANSWER_REFERENCE_UNKNOWN", [], "Linksabbieger vs. entgegenkommender Rechtsabbieger - 'Ich'"),
    "H012": ("CONDITION_EXTRACTION", ["PARAPHRASE_MISMATCH"], "Blaulicht ohne Martinshorn - 'Es warnt'"),
    "H013": ("ANSWER_REFERENCE_UNKNOWN", [], "Ampel vs. Vorfahrtsschild - Antworten 'Die Ampel'/'Das Schild'"),
    "H014": ("CONDITION_EXTRACTION", ["PARAPHRASE_MISMATCH"], "Ampel ausgefallen - Verkehrszeichen gelten"),
    "H015": ("CONTRARY_NOT_DERIVABLE", [], "Gelb - 'beschleunigen' widerspricht"),
    "H016": ("CONTRARY_NOT_DERIVABLE", [], "Arm hoch, in der Kreuzung - 'anhalten' widerspricht 'räumen'"),
    "H017": ("CONTRARY_NOT_DERIVABLE", [], "Bus fährt ab - 'Vorrang, weiterfahren' widerspricht"),
    "H018": ("QUESTION_TYPE_UNKNOWN", ["PARAPHRASE_MISMATCH"], "'Was ist verboten?' + Infinitiv-Antwort 'Ihn zu überholen'"),
    "H019": ("CONTRARY_NOT_DERIVABLE", [], "Pfeifsignal - 'zügig überqueren' widerspricht 'warten'"),
    "H020": ("ANSWER_REFERENCE_UNKNOWN", [], "Vorrang am Andreaskreuz - 'Der Straßenverkehr'"),
    "H021": ("YES_NO_PROPOSITION", [], "Stau am Zebrastreifen - 'Nein'"),
    "H022": ("PARAPHRASE_MISMATCH", [], "verkehrsberuhigten Bereich verlassen - Gefährdung ausschließen"),
    "H024": ("YES_NO_PROPOSITION", [], "Verzicht auf Vorfahrt - 'Ja'"),
    "H025": ("YES_NO_PROPOSITION", [], "Blinken bei Einfahrt Kreisverkehr - 'Nein, unzulässig'"),
    "H026": ("SIGN_NAME_MATCH", [], "Zeichen 205"),
    "H027": ("SIGN_NAME_MATCH", [], "Zeichen 267 - Verwechslung Einbahnstraße"),
    "H029": ("SIGN_NAME_MATCH", [], "Zeichen 237 - Gefahrzeichen-Verwechslung"),
    "H030": ("SIGN_NAME_MATCH", [], "Zeichen 220"),
    "H033": ("PARAPHRASE_MISMATCH", [], "Geltungsbeginn von Vorschriftzeichen 'ab dem Standort'"),
    "H034": ("CONTRARY_NOT_DERIVABLE", [], "Zeichen 277.1 - 'nur Lkw nicht überholen' widerspricht"),
    "H036": ("NUMERIC_CONTEXT", [], "dreistreifige Bake"),
    "H037": ("NUMERIC_CONTEXT", ["CONDITION_EXTRACTION"], "Andreaskreuz außerorts 50 m - Bedingung 'außerorts'"),
    "H039": ("PARAPHRASE_MISMATCH", [], "Ausscheren ankündigen 'mit dem Blinker'"),
    "H040": ("ANSWER_REFERENCE_UNKNOWN", [], "Straßenbahn überholen - 'Rechts'/'Links'"),
    "H041": ("ANSWER_REFERENCE_UNKNOWN", [], "eingeordneter Linksabbieger - 'Rechts'/'Links'"),
    "H042": ("YES_NO_PROPOSITION", [], "Einfädelungsstreifen schneller - 'Ja'"),
    "H044": ("PARAPHRASE_MISMATCH", [], "Rückwärtsfahren, schlechte Sicht - 'einweisen lassen'"),
    "H045": ("PARAPHRASE_MISMATCH", [], "Fahrstreifenwechsel - 'andere nicht gefährden'"),
    "H046": ("PARAPHRASE_MISMATCH", [], "Warnblinklicht - 'bei Annäherung an einen Stau'"),
    "H048": ("CONTRARY_NOT_DERIVABLE", ["QUESTION_TYPE_UNKNOWN"], "Halten unzulässig - 'ruhige Seitenstraße' nicht widerlegt"),
    "H049": ("NUMERIC_CONTEXT", [], "Fußgängerüberweg 5 m Halteverbot"),
    "H050": ("CONTRARY_NOT_DERIVABLE", [], "Parklücke - 'der andere, weil schneller' widerspricht"),
    "H051": ("CONTRARY_NOT_DERIVABLE", [], "Beleuchtung haltender Fahrzeuge außerorts"),
    "H052": ("PARAPHRASE_MISMATCH", [], "Unfallbeteiligter - Definition umformuliert"),
    "H053": ("YES_NO_PROPOSITION", [], "Unfallspuren beseitigen - 'Nein'"),
    "H054": ("YES_NO_PROPOSITION", [], "Motorrad abschleppen - 'Nein'"),
    "H055": ("CONTRARY_NOT_DERIVABLE", [], "verlorene Erde - 'nichts tun' widerspricht"),
    "H057": ("PARAPHRASE_MISMATCH", [], "Abblendlicht am Tag bei Sichtbehinderung"),
    "H058": ("YES_NO_PROPOSITION", [], "nur Standlicht - 'Nein'"),
    "H059": ("NUMERIC_CONTEXT", [], "Höhe Fahrzeug + Ladung 4 m"),
    "H062": ("YES_NO_PROPOSITION", [], "Smartphone mit Sprachsteuerung - 'Ja'"),
    "H063": ("YES_NO_PROPOSITION", [], "Radarwarner - 'Nein'"),
    "H064": ("CONTRARY_NOT_DERIVABLE", [], "Ladungssicherung - 'normale Fahrt reicht' widerspricht"),
    "H065": ("CONDITION_EXTRACTION", ["NUMERIC_CONTEXT"], "Gehweg-Alter 10 vs. 8 (müssen vs. dürfen)"),
    "H069": ("YES_NO_PROPOSITION", [], "Gurtpflicht beim Rangieren - 'Nein, Ausnahme'"),
    "H070": ("CONTRARY_NOT_DERIVABLE", [], "Personen im Pkw - 'so viele wie hineinpassen'"),
    "H071": ("YES_NO_PROPOSITION", [], "Seitenstreifen Teil der Fahrbahn - 'Nein'"),
    "H072": ("YES_NO_PROPOSITION", [], "Fußgänger auf Autobahn - 'Nein'"),
    "H073": ("CONTRARY_NOT_DERIVABLE", ["NUMERIC_CONTEXT"], "Anhänger abstellen - 'vier Wochen'"),
    "H074": ("CONTRARY_NOT_DERIVABLE", [], "Gespann 9 m - 'immer links fahren'"),
    "H075": ("SOURCE_UNVERIFIED", [], "Punkte (StVG)"),
    "H076": ("PARAPHRASE_MISMATCH", [], "Alkoholwirkung - 'längere Reaktionszeit'"),
    "H077": ("PARAPHRASE_MISMATCH", [], "Medikamente - Beipackzettel"),
    "H078": ("CONTRARY_NOT_DERIVABLE", [], "Lebenslanges Lernen - 'Wissen reicht für immer'"),
    "H079": ("QUESTION_TYPE_UNKNOWN", ["PARAPHRASE_MISMATCH"], "'Welche Aussage ist falsch?' - Rechtsüberholen Autobahn"),
    "H080": ("QUESTION_TYPE_UNKNOWN", [], "'Was ist am Stoppschild NICHT erlaubt?'"),
}
