"""Norm coverage audit: which provisions of the official texts does the knowledge base cover?

    python tools/analysis/norm_coverage.py   -> reports/norm_coverage.md (+ .json)

Every exam-relevant norm of the official snapshots (StVO §§ 1-43 and Anlagen, eKFV, the cited StVZO norms) is cut
into provisions (paragraph '(n)', with enumerations '1.', '2.' joined to their lead sentence). A provision counts
as covered when a knowledge object cites it with evidence taken from it, or when a rule/claim states it (content
overlap). The uncovered provisions are the systematic to-do list - knowledge is added per norm, from the official
text, never from test questions.
"""

from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from smart360.theory.kb import KnowledgeBase
from smart360.theory.text import content

ROOT = Path(__file__).resolve().parents[3]
STVO_EXAM = {f"§ {n}" for n in [*range(1, 44), "7a", "15a", "21a", "36a"]}


def provisions(text: str) -> list[str]:
    """'(1) Lead 1. a 2. b (2) …' -> ['(1) Lead a; b', '(2) …']"""
    parts = re.split(r"\n(?=\(\d+[a-z]?\)\n)", "\n" + text.strip())
    out = []
    for p in parts:
        p = re.sub(r"\n(\d+[a-z]?\.|[a-z]\)|[a-z]{2}\))\n", " ", p.strip())
        p = re.sub(r"\s+", " ", p).strip()
        if len(p) > 25:
            out.append(p)
    return out


def norms_in_scope(kb: KnowledgeBase) -> list[tuple[str, str, str]]:
    cited = defaultdict(set)
    for it in [*kb.objects.values(), *kb.numeric.values(), *kb.signs.values()]:
        for s in it.sources:
            if s.law:
                cited[s.law].add(s.norm or "")
    out = []
    for law, snap in kb.snapshots.items():
        for key, n in snap["norms"].items():
            if law == "stvo_2013":
                if not (key in STVO_EXAM or key.startswith("Anlage")):
                    continue
                if key.startswith("Anlage") and " Nr." not in key:
                    continue  # the numbered entries are the provisions
            elif law == "stvzo_2012" and key not in cited[law]:
                continue
            out.append((law, key, n["text"]))
    return out


def main() -> int:
    kb = KnowledgeBase.load()
    evidence = defaultdict(list)
    for it in [*kb.objects.values(), *kb.numeric.values(), *kb.signs.values()]:
        for s in it.sources:
            if s.law and s.evidence:
                evidence[(s.law, s.norm or "")].append(re.sub(r"\s+", " ", s.evidence))
    kb_texts = [content(" ".join([o.rule, *(" ".join(c.context) + " " + c.statement for c in o.claims)]))
                for o in kb.objects.values()]
    kb_texts += [content(sg.meaning) for sg in kb.signs.values() if "Amtliche Bezeichnung" not in sg.meaning]
    rows = []
    for law, key, text in norms_in_scope(kb):
        for p in provisions(text):
            pw = content(p)
            by_ev = any(e[:60] in p or p[:60] in e for e in evidence.get((law, key), []))
            by_text = any(len(pw & kw) / max(1, len(pw)) >= 0.5 for kw in kb_texts) if len(pw) >= 4 else False
            rows.append({"law": law, "norm": key, "provision": p[:400], "covered": by_ev or by_text,
                         "by_evidence": by_ev})
    per_norm: dict[tuple[str, str], list[dict]] = defaultdict(list)
    for r in rows:
        per_norm[(r["law"], r["norm"])].append(r)
    total, cov = len(rows), sum(r["covered"] for r in rows)
    lines = ["# Norm coverage of the knowledge base", "",
             f"{cov} of {total} exam-relevant provisions covered ({cov / total:.0%}). Covered = cited with evidence "
             "from the provision, or stated by a rule/claim (content overlap >= 50 %). Generated by "
             "`windows/tools/analysis/norm_coverage.py`.", "",
             "| Law | Norm | Provisions | Covered | Uncovered (start of text) |", "|---|---|---|---|---|"]
    for (law, key), rs in sorted(per_norm.items(), key=lambda x: (x[0][0], _sort_key(x[0][1]))):
        unc = [r["provision"][:90] for r in rs if not r["covered"]]
        lines.append(f"| {law} | {key} | {len(rs)} | {sum(r['covered'] for r in rs)} | "
                     f"{'<br>'.join(u.replace('|', '/') for u in unc[:4]) or '-'}{' …' if len(unc) > 4 else ''} |")
    (ROOT / "reports" / "norm_coverage.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    (ROOT / "reports" / "norm_coverage.json").write_text(json.dumps(rows, ensure_ascii=False, indent=1) + "\n",
                                                        encoding="utf-8")
    print(f"{cov}/{total} provisions covered")
    return 0


def _sort_key(norm: str) -> tuple:
    m = re.match(r"(§|Anlage)\s*(\d+)([a-z]?)(?:\s*Nr\.\s*([\d.]+))?", norm)
    if not m:
        return (9, 0, "", 0.0)
    nr = m.group(4) or "0"
    try:
        nrf = float(nr.split(".")[0] + "." + "".join(nr.split(".")[1:])) if "." in nr else float(nr)
    except ValueError:
        nrf = 0.0
    return (0 if m.group(1) == "§" else 1, int(m.group(2)), m.group(3), nrf)


if __name__ == "__main__":
    raise SystemExit(main())
